package com.juaracoding.utils;

public enum TestCases {
    TL001("TL001 Login Page Displayed With URL Valid"),
    TL002("TL002 Login Page No Displayed With URL Invalid"),
    TL004("TL004 User Input Invalid Username And Password"),
    TL005("TL005 User Login Without Input Username"),
    TL006("TL006 User Login Without Input Password"),
    TL008("TL008 User Input Username And Password Just Space"),
    TL003("TL003 User Input Valid Username And Password"),
    TH001("TH001 User Go To Internal Page From Internal Card More Info"),
    TH002("TH002 User Go To Eksternal Page From Eksternal Card More Info"),
    TH003("TH003 User Go To Perizinan From Perizinan Card More Info"),
    TH004("TH004 Value Internal Document Card Same Like Value Internal Document Page"),
    TH005("TH005 Value Eksternal Document Card Same Like Value Eksternal Document Page"),
    TH006("TH006 Value Perizinan Card Same Like Value Perizinan Page"),
    TH007("TH007 User Go To Home Page From Side Bar Menu Home"),
    TH008("TH008 User Go To Home Page From Icon Home"),
    TD001("TD001 User menuju Departemen Page melalui Side Bar Menu Data Master"),
    TD003("TD003 User Input Data Departemen"),
    TD004("TD004 User Input Data Nama Departemen dengan Kosong"),
    TD009("TD009 User Batal Input Data Deprtemen dengan Pilih Tombol Close"),
    TD010("TD010 User Batal Input Data Departemen Dengan Tombol X"),
    TGD001("TGD001 User Go To Group Dokumen Page"),
    TGD002("TGD002 User Search Some Document In Group Documents"),
    TGD005("TGD005 User Input Data Group Dokumen"),
    TGD017("TGD017 User Cancel Input Data Group Dokumen With Button Close"),
    TLP001("TLP001 User Go To Lokasi Penyimpanan page from Side Bar Menu"),
    TLP002("TLP002 User Search Some Lokasi Penyimpanan"),
    TLP003("TLP003 User Input Data Name Lokasi Penyimpanan"),
    TLP004("TLP004 User Input Data Lokasi Penyimpanan Name With Empty"),
    TLP005("TLP005 User Input Data Lokasi Penyimpanan Name With Same Name"),
    TLP006("TLP006 User Input Data Lokasi Penyimpanan Name With Space"),
    TLP007("TLP007 User Input Data Lokasi Penyimpanan Name With Spesial Character"),
    TLP008("TLP008 Show Modal Input Data"),
    TLP009("TLP009 User Cancel Input Data Lokasi Penyimpanan With Click Button Close"),
    TLP010("TLP010 User Cancel Input Data Lokasi Penyimpanan With Click X"),
    TLP011("TLP011 User Edit Data Lokasi Penyimpanan"),
    TLP012("TLP012 User Edit Data Nama Lokasi Penyimpanan With Same Name"),
    TLP013("TLP013 User Edit Data Nama Lokasi Penyimpanan With Special Character"),
    TLP014("TLP014 User Edit Data Nama With Space"),
    TLP015("TLP015 User Edit Data Nama With Empty"),
    TLP016("TLP016 User Cancel Edit Data Lokasi Penyimpanan With Click Button Cancel"),
    TLP017("TLP017 User Cancel Edit Data Lokasi Penyimpanan With Click Button X"),
    TLP018("TLP018 User Go To Home page from Icon Home Lokasi Penyimpanan"),
    MM001("MM001 User Go To Data Media Arsip"),
    MM002("MM002 User Input Data"),
    TT001("TT001 User Go To Template Page"),
    TT002("TT002 User Search Some Template"),
    TT003("TT003 User Input Data Kategory Internal And Departement Business Development Template"),
    TT004("TT004 User Input Data Kategory Internal And Departement HRD Template"),
    TT005("TT005 User Input Data Kategory Internal And Departement Direksi Template"),
    TT006("TT006 User Input Data Kategory Eksternal And Departement Business Development Template"),
    TT007("TT007 User Input Data Kategory Eksternal And Departement HRD Template"),
    TT008("TT008 User Input Data Kategory Eksternal And Departement Direksi Template"),
    TT009("TT009 User Cancel Input Data Template With Button Close"),
    TT010("TT010 User Cancel Input Data Template With Button X"),
    TT011("TT011 User Edit Data Kategory Internal And Departement Business Development Template"),
    TT012("TT012 User Edit Data Kategory Internal And Departement HRD Template"),
    TT013("TT013 User Edit Data Kategory Internal And Departement Direksi Template"),
    TT014("TT014 User Edit Data Kategory Eksternal And Departement Business Development Template"),
    TT015("TT015 User Edit Data Kategory Eksternal And Departement HRD Template"),
    TT016("TT016 User Edit Data Kategory Eksternal And Departement Direksi Template"),
    TT017("TT017 User Cancel Edit Data Template With Button Close"),
    TT018("TT018 User Cancel Edit Data Template With Button X"),
    ID001("ID001 User Go To Internal Page From Internal"),
    ID002("ID002 User Go To Dokumen Internal Page From Internal"),
    ID003("ID003 User Input Data Internal Dokumen Share Ya"),
    ID004("ID004 User Input Data Internal Dokumen Share Tidak"),
    ID005("ID005 User Input Data Kosong"),
    ID007("ID007 User Tidak Klik List Group Dokumen"),
    ID008("ID008 User Tidak Input Nama Dokumen "),
    ID009("ID009 User Tidak Input Deskripsi Dokumen"),
    ID010("ID010 User Tidak Klik Tanggal Mulai"),
    ID011("ID011 User Tidak Klik Tanggal Berakhir"),
    ID012("ID012 User Tidak Input Owner Dokumen"),
    ID013("ID013 User Tidak Pilih Tanggal Dokumen"),
    ID014("ID014 User Tidak Klik List Lokasi Arsip"),
    ID015("ID015 User Tidak Klik Tanggal Reminder"),
    ID016("ID016 User Tidak Klik List Jenis Media"),
    ID018("ID018 User Melakukan View Data"),
    ID019("ID019 User Melakukan View File"),
    ID020("ID020 User Tidak Merubah Data Pada Edit Data"),
    ID021("ID021 User Melakukan Edit Data Lokasi Arsip"),
    ID022("ID022 User Melakukan Edit Data Jenis Media"),
    ID023("ID023 User Mengedit Upload File"),
    ID024("ID024 User Klik Button Filter"),
    ID025("ID025 User Memfilter Memasukkan Nomor Dokumen Dengan Dokumen Tidak Ada"),
    ID026("ID026 User Memfilter Memasukkan Nomor Dokumen Dengan Dokumen Ada"),
    ID027("ID027 User Showing Data Entries 25"),
    ID028("ID028 User Showing Data Entries 50"),
    ID029("ID029 User Showing Data Entries 100"),
    ED001("ED001 User Go To Eksternal Page"),
    ED024("ED024 User Filter Some Documents Eksternal"),
    ED027("ED027 Show Input Data Page Documents Eksternal"),
    ED003("ED003 User Input Data Eksternal Share Ya Status Aktif"),
    TP001("TP001 User Mengunjungi Halaman Perizinan menggunakan Sidebar Menu"),
    TP002("TP002 User mengunjungi halaman Input Data Perizinan"),
    TP003("TP003 User Berhasil Menambahkan Data Perizinan"),
    TP004("TP004 User Tidak Memasukkan Data Apapun"),
    TP005("TP005 User Tidak input Nomor Perizinan"),
    TP006("TP006 User Tidak Input Nama Perizinan"),
    TP007("TP007 User Tidak Input Tanggal Mulai"),
    TP008("TP008 User Tidak Input Tanggal Akhir"),
    TP009("TP009 User Tidak Input Diterbitkan Oleh"),
    TP010("TP010 User Tidak Input Deskripsi"),
    TP011("TP011 User Tidak Input Pemilik Dokumen"),
    TP012("TP012 User Tidak Input Dibuat Oleh"),
    TP013("TP013 User Tidak Input Tim Terkait"),
    TP014("TP014 User Tidak Input Tanggal Reminder"),
    TP015("TP015 User Tidak Input Jenis Media"),
    TP016("TP016 User Input Tanggal Berakhir Di Bawah Tanggal Mulai"),
    TP017("TP017 User Input Tanggal Reminder Di Bawah Tanggal Mulai"),
    TP018("TP018 User Menambahkan File PDF"),
    TP019("TP019 User Menambahkan File DOCX"),
    TP020("TP020 User Hanya Memasukkan Data Kosong dan Invalid"),
    TP021("TP021 User Tidak Memilih Share dengan Departemen"),
    TP022("TP022 User Hanya Memasukkan Data Kosong dan Invalid"),
    TP023("TP023 User Mencari berdasarkan Nomor Perizinan"),
    TP024("TP024 User Mencari berdasarkan Nama Perizinan"),
    TP025("TP025 User Mencari berdasarkan Departemen"),
    TP026("TP026 User Mencari berdasarkan File yang Ada"),
    TP027("TP027 User Mencari berdasarkan File yang Tidak Ada"),
    TP028("TP028 User Mencari berdasarkan Nomor Perizinan Invalid"),
    TP029("TP029 User Mencari berdasarkan Nama Perizinan Invalid"),
    TP030("TP030 User ke Halaman View Data"),
    TP031("TP031 User Melihat File DOCX yang sudah Ditambahkan"),
    TP032("TP032 User Melihat File PDF yang sudah Ditambahkan"),
    TP033("TP033 User ke Halaman Edit Data"),
    TL009("TL009 User Logout");

    private String testCaseName;

    TestCases(String value) {
        testCaseName = value;
    }

    public String getTestCaseName() {
        return testCaseName;
    }

}
